name: Setup environment
description: Setup pnpm, NodeJS, install and cache dependencies

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2

    - name: Install NodeJS
      uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
        cache: pnpm

    - name: Install dependencies
      shell: sh
      run: pnpm install
