const { defineConfig } = require("eslint-define-config");

module.exports = defineConfig({
  ignorePatterns: ["*.json", "*.yml", "*.yaml", "*.html"],
  env: {
    es2021: true,
    "shared-node-browser": true,
  },
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaFeatures: {
      impliedStrict: true,
    },
  },
  plugins: [
    "@typescript-eslint",
    "import",
    "simple-import-sort",
    "functional",
    "promise",
    "regexp",
    "sonarjs",
    "unicorn",
    "github",
    "array-func",
    "eslint-comments",
    "no-secrets",
  ],
  extends: [
    "eslint:all",
    "plugin:@typescript-eslint/recommended",
    "plugin:import/recommended",
    "plugin:functional/external-recommended",
    "plugin:functional/recommended",
    "plugin:functional/stylistic",
    "plugin:promise/recommended",
    "plugin:regexp/recommended",
    "plugin:sonarjs/recommended",
    "plugin:unicorn/all",
    "plugin:github/recommended",
    "plugin:array-func/all",
    "plugin:eslint-comments/recommended",
  ],
  rules: {
    "import/first": "error",
    "import/no-deprecated": "error",
    "import/no-mutable-exports": "error",
    "import/no-cycle": "error",
    "import/no-internal-modules": "error",
    "import/no-unused-modules": "error",
    "import/no-relative-parent-imports": "error",
    "import/no-self-import": "error",
    "import/no-useless-path-segments": "error",
    "import/newline-after-import": "error",
    "import/no-duplicates": "error",
    "import/no-default-export": "error",
    "import/no-named-default": "error",
    "import/no-unassigned-import": "error",
    "simple-import-sort/imports": "error",
    "simple-import-sort/exports": "error",
    "eslint-comments/no-use": "error",
    "eslint-comments/require-description": "error",
    "no-secrets/no-secrets": "error",
  },
  settings: {
    "import/extensions": [".js", ".mjs", ".jsx", "*.ts", "*.tsx"],
  },
});
