name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  continuous-integration:
    name: Continuous Integration
    uses: ./.github/workflows/run-on-nx-cloud.yml
    secrets: inherit
    with:
      number-of-agents: 3
      command: >
        pnpm nx affected --parallel 3 --target lint:prettier &
        pnpm nx affected --parallel 3 --target lint:eslint
