name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup-environment:
    name: Setup environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs:
      - setup-environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Run Prettier on workspace packages
        run: pnpm --recursive lint:prettier

      - name: Run Prettier on workspace root
        run: pnpm --workspace-root lint:prettier

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    needs:
      - setup-environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Run ESLint on workspace packages
        run: pnpm --recursive lint:eslint

      - name: Run ESLint on workspace root
        run: pnpm --workspace-root lint:eslint
