name: Run on NX Cloud

on:
  workflow_call:
    secrets:
      NX_CLOUD_ACCESS_TOKEN:
        required: true
    inputs:
      number-of-agents:
        type: number
        required: true
      run:
        type: string
        required: true

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_BRANCH: ${{ github.event.number || github.ref_name }}
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  coordinator:
    name: Nx Cloud - Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for NX Cloud
        uses: nrwl/nx-set-shas@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Start NX Cloud agents
        run: pnpm nx-cloud start-ci-run

      - name: Run workflow
        run: ${{ inputs.run }}

      - name: Stop NX Cloud agents
        if: ${{ always() }}
        run: pnpm nx-cloud stop-all-agents

  setup-agents-matrix:
    name: Nx Cloud - Setup Agents
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-agents-matrix.outputs.matrix }}
    steps:
      - name: Set agents matrix
        id: set-agents-matrix
        run: |
          AGENTS_JSON_ARRAY=$(node -e "console.log(JSON.stringify(Array.from(new Array(${{ inputs.number-of-agents }})).map((_, i) => i + 1)));")
          echo $AGENTS_JSON_ARRAY
          echo "matrix=$AGENTS_JSON_ARRAY" >> $GITHUB_OUTPUT

  agents:
    name: Nx Cloud - Agent ${{ matrix.agent }}
    runs-on: ubuntu-latest
    needs:
      - setup-agents-matrix
    strategy:
      matrix:
        agent:
          - ${{ fromJson(needs.setup-agents-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Start NX Cloud - Agent ${{ matrix.agent }}
        run: pnpm nx-cloud start-agent
        env:
          NX_AGENT_NAME: ${{ matrix.agent }}
